### ISSUE TITLE
Cloud rclone update worker

### ISSUE THREAD

**Issue by pisuke** [LUSHDigital/lrpi_rclone#8]
Set up an app engine to run at set intervals (1 hour?) or on file updates to generate content.json files.
Alternatively set up the player to generate the content.json files at regular intervals while not playing.

**Comment by paulharter** [comment]
- researched change callbacks for files
- created and deployed simple GEA app

**Comment by pisuke** [comment]
@paulharter @InBrewJ  Better to do it with a different fix where we remove content.json tracks from GDrive and generate them with Server.py in the player container.
For filtering out content.json files, rclone offers good filtering rules.
https://rclone.org/filtering/

**Comment by paulharter** [comment]
creating content listing on the fly in the player instead

**Comment by pisuke** [comment]
Just added a line to avoid showing up hidden files and dirs. Seems to work well!
